### PR TITLE
Match type exactly when checking TYPES_WITH_SAFE_REPR

### LINKED ISSUE #98: Can't wrap function with StrEnum as argument with default
This issue is similar to #63 

```python
from enum import StrEnum
from makefun import wraps

class A(StrEnum):
    a = 'a'

def foo(a=A.a):
    pass

@wraps(foo)
def test(*args, **kwargs):
    return foo(*args, **kwargs)
```

When this runs it throws:
```
Error in generated code:
def foo(a=<A.a: 'a'>):
    return _func_impl_(a=a)

Traceback (most recent call last):
  File "/home/alexeyd/a.py", line 10, in <module>
    @wraps(foo)
     ^^^^^^^^^^
  File "/usr/python3.11/lib/python3.11/site-packages/makefun/main.py", line 1062, in replace_f
    return create_function(func_signature=func_signature,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/python3.11/lib/python3.11/site-packages/makefun/main.py", line 323, in create_function
    f = _make(co_name, params_names, body, evaldict)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/python3.11/lib/python3.11/site-packages/makefun/main.py", line 714, in _make
    code = compile(body, filename, 'single')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<makefun-gen-0>", line 1
    def foo(a=<A.a: 'a'>):
              ^
SyntaxError: invalid syntax
```

The problem is StrEnum is also an str (that's a point of the class), so [here](https://github.com/smarie/python-makefun/blob/525ce1fa6239899d3cd6c83aba54504c091767d7/src/makefun/main.py#L469) it is assumed to have safe repr.

I propose to change the check from checking isinstance to checking ```type(symbol) in TYPES_WITH_SAFE_REPR```

### PR DESCRIPTION
**Pull request by moskupols**
This fixes #98 

My understanding is that here we are trying to say whether a builtin literal for str, int, bytes, or bool would produce the same value as given. However, that is only possible if the given value has one of these types.

### CODE REVIEW

**Comment by smarie** [comment]
Hi @moskupols thanks for this Proposal ! Indeed it makes sense.
Could you please update your branch to the latest  ? I just switched the nox backend to virtualenv for convenience. Note that you'll need "nox==2022.11.21" and "virtualenv==16" to be able to create all nox sessions including those for python 2.7, 3.5 3.6 and 3.7.

**Comment by moskupols** [comment]
Hi @smarie !
I've just merged main and updated the test so that it runs on earlier versions of python as well.

**Comment by moskupols** [comment]
Hi @smarie ! Is there a chance to merge the PR?

**Comment by smarie** [comment]
Thanks @moskupols and sorry for the delay !

**Comment by smarie** [comment]
Hi @AlexeyDmitriev  and @moskupols , thanks for your feedback ! I was expecting to release it just after merging yesterday, but unfortunately there is an issue in my build system (#105 ). I'll try to find 15' to fix this by the end of the week, hopefully it is just a matter of getting rid of nox_utils.py and using the proper nox.parametrize routines, now that they are available.

**Comment by smarie** [comment]
1.15.3 is now released

**Pull request merged**
